{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "10.15.3"
  ],
  "cache": {
    "npm": true
  },
  "install": [
    "yarn"
  ],
  "script": [
    "npm run test -- --coverage",
    "npm run build"
  ],
  "after_success": [
    "CODECOV_TOKEN=$codecov_token npm run report-coverage"
  ],
  "after_script": [
    "COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls"
  ],
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "local_dir": "build",
      "on": {
        "branch": [
          "master"
        ]
      },
      "skip_cleanup": true,
      "token": "$GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}"
    }
  ]
}
